### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by anqurvanillapy** [PragmaTwice/ichigo-lang#1]
`s/DENPENDENT/DEPENDENT/g`

- BTW,
    + why there aren't signatures for declarations?
    + why there are separate cases with different types?  Would this make the lambda harder to type?

**Comment by PragmaTwice** [comment]
Typo'll be fixed soon, thanks for questions

> why there aren't signatures for declarations?

Unnecessary. It's not a usable language, so I care little about readability and others.
But you can give signatures for expressions easily, like `expr : type`.
So you can implement it by another way `one = 1 : nat`
 
> why there are separate cases with different types? Would this make the lambda harder to type?

Because I cannot find an awesome grammar to write the type of parameters in different cases only once.
233

**Comment by anqurvanillapy** [comment]
Closed for typos being fixed.
